# Configuracion MySQL - GlassCore
db.url=jdbc:mysql://localhost:3306/glasscore_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Tegucigalpa&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
db.user=root
db.password=
